#!/bin/bash

# https://www.viget.com/articles/two-ways-to-share-git-hooks-with-your-team/
# Set the git hooks path
# git config core.hooksPath .githooks

# Set your git tags
# git tag -a "0.0.1"

# run from the root of the repo
.githooks/replace_by_git_vars.py README.template README.md

# Example:
# [![Integration Tests](https://github.com/{{ repository.name }}/actions/workflows/integration-tests.yaml/badge.svg?branch={{ current.branch }})](https://github.com/{{ repository.name }}/actions/workflows/integration-tests.yaml?query=branch%3A{{ current.branch }})
