#!/bin/bash

# Set the git hooks path
# git config core.hooksPath .githooks
if [[ -z "$(git config core.hooksPath)" ]]; then
  git config core.hooksPath .githooks
fi

# Set your git tags
# git tag -a "0.0.1"
if [[ -z "$(git describe | grep -Eio '([0-9]+\.)+[0-9]+')" ]]; then
  git tag -a "0.0.1" -m "version 0.0.1"
fi


# run from the root of the repo
git config current.version "$(git describe | grep -Eio '([0-9]+\.)+[0-9]+')"
.githooks/replace_by_git_vars.py README.template README.md

# Example:
# [![Integration Tests](https://github.com/{{ repository.name }}/actions/workflows/integration-tests.yaml/badge.svg?branch={{ current.branch }})](https://github.com/{{ repository.name }}/actions/workflows/integration-tests.yaml?query=branch%3A{{ current.branch }})
