#!/usr/bin/env bash
# Auto-generated from iOS captures 2026-08-02
# Full JWT refresh tokens - never commit to repo
set -euo pipefail

gh secret set PSS_ACCOUNT_1_EMAIL -b "syn@syncpool.com"
gh secret set PSS_ACCOUNT_1_PASSWORD -b "Zydvux-texqep-1bimty"
gh secret set PSS_ACCOUNT_1_REFRESH_TOKEN -b "eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI5MjI4ODM0IiwiZGV2aWNlS2V5IjoiQ0MzQzc2NDItRTZGRS00NzM3LTg4QzEtMTMwMzk1NzYwQjUyIiwiZW1haWwiOiJzeW5Ac3luY3Bvb2wuY29tIiwiY3JlYXRlZERhdGUiOiIyMDI2LTA4LTAyVDE3OjA5OjI3In0.1tb3af-ID09uLbvCt5oMOLOleaPVLzsgjmgXQv1jL-c"

gh secret set PSS_ACCOUNT_2_EMAIL -b "rst@syncpool.com"
gh secret set PSS_ACCOUNT_2_PASSWORD -b "jecqew-vejtus-3kIxtu"
gh secret set PSS_ACCOUNT_2_REFRESH_TOKEN -b "eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI5MjM4MTQ5IiwiZGV2aWNlS2V5IjoiQ0MzQzc2NDItRTZGRS00NzM3LTg4QzEtMTMwMzk1NzYwQjUyIiwiZW1haWwiOiJyc3RAc3luY3Bvb2wuY29tIiwiY3JlYXRlZERhdGUiOiIyMDI2LTA4LTAyVDE3OjEwOjEzIn0.4YpsfkDBTEHwZd2QXRRvasHPteyiSP-l7yKLne-iPcs"

gh secret set PSS_ACCOUNT_3_EMAIL -b "raell.dottin@gmail.com"
gh secret set PSS_ACCOUNT_3_PASSWORD -b "jabpa1-viqcid-xeqqUp"
gh secret set PSS_ACCOUNT_3_REFRESH_TOKEN -b "eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIzNDMwODkyIiwiZGV2aWNlS2V5IjoiQ0MzQzc2NDItRTZGRS00NzM3LTg4QzEtMTMwMzk1NzYwQjUyIiwiZW1haWwiOiJyYWVsbC5kb3R0aW5AZ21haWwuY29tIiwiY3JlYXRlZERhdGUiOiIyMDI2LTA4LTAyVDE3OjExOjA0In0.SkM6ZLm9_8z6ydwlxqtcoHnQ_cVaEOklc-k0MyHGAG4"

gh secret set PSS_ACCOUNT_4_EMAIL -b "fin@syncpool.com"
gh secret set PSS_ACCOUNT_4_PASSWORD -b "sugwuj-byndab-xiRke2"
gh secret set PSS_ACCOUNT_4_REFRESH_TOKEN -b "eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI5MjMxNzA4IiwiZGV2aWNlS2V5IjoiQ0MzQzc2NDItRTZGRS00NzM3LTg4QzEtMTMwMzk1NzYwQjUyIiwiZW1haWwiOiJmaW5Ac3luY3Bvb2wuY29tIiwiY3JlYXRlZERhdGUiOiIyMDI2LTA4LTAyVDE3OjExOjM4In0.f1g3_fJFoRwvju7nCFt9dnY2pj1jjtrkNiVkkFZ96fc"

gh secret set PSS_ACCOUNT_5_EMAIL -b "ack@syncpool.com"
gh secret set PSS_ACCOUNT_5_PASSWORD -b "cymfe0-mifkUn-mymhix"
gh secret set PSS_ACCOUNT_5_REFRESH_TOKEN -b "eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI5MTgxNDMwIiwiZGV2aWNlS2V5IjoiQ0MzQzc2NDItRTZGRS00NzM3LTg4QzEtMTMwMzk1NzYwQjUyIiwiZW1haWwiOiJhY2tAc3luY3Bvb2wuY29tIiwiY3JlYXRlZERhdGUiOiIyMDI2LTA4LTAyVDE3OjEyOjIzIn0.5bdfCRCLA0OMiq0fI-Sl2eoaMiyy9dS91EYGYDuIvLk"

